// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6MmENZ7Sk0K79kgZ8xXia0BuuT0SVGA8',
    appId: '1:761484217666:web:c8515c2333d54ed167ccdb',
    messagingSenderId: '761484217666',
    projectId: 'gwinews-development',
    authDomain: 'gwinews-development.firebaseapp.com',
    storageBucket: 'gwinews-development.appspot.com',
    measurementId: 'G-XE4D9VZC7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZAk3SOBlXNYkCeXIHxIVrJN-Jp0vGCE',
    appId: '1:761484217666:android:6f7ea93dbe56f71467ccdb',
    messagingSenderId: '761484217666',
    projectId: 'gwinews-development',
    storageBucket: 'gwinews-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxSaTSkFYyZ1V5NaoCzG5HcElPcMjjNA',
    appId: '1:761484217666:ios:010c93cd6a2a44d667ccdb',
    messagingSenderId: '761484217666',
    projectId: 'gwinews-development',
    storageBucket: 'gwinews-development.appspot.com',
    iosBundleId: 'com.example.semestre5Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxSaTSkFYyZ1V5NaoCzG5HcElPcMjjNA',
    appId: '1:761484217666:ios:010c93cd6a2a44d667ccdb',
    messagingSenderId: '761484217666',
    projectId: 'gwinews-development',
    storageBucket: 'gwinews-development.appspot.com',
    iosBundleId: 'com.example.semestre5Mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB58GozwXyXncT05RCtf_UwoHSPO6XlmqE',
    appId: '1:761484217666:web:f4e3aea3ac3f63ac67ccdb',
    messagingSenderId: '761484217666',
    projectId: 'gwinews-development',
    authDomain: 'gwinews-development.firebaseapp.com',
    storageBucket: 'gwinews-development.appspot.com',
    measurementId: 'G-N969VZQGWE',
  );
}
